# scripts/windows/create-seed.ps1
# Creates apps/backend/.local-superusers.env with local demo credentials if missing.
# These are intentionally shared local-only demo accounts, not production secrets.
# Called by setup-and-start.bat. Must run from repo root.
#
# IMPORTANT: Uses WriteAllLines with explicit UTF-8 no-BOM encoding.
# Windows PowerShell 5.1 default UTF8 output adds a BOM which corrupts the first key
# when Python reads the file. WriteAllLines + UTF8Encoding($false) avoids this.

$seedFile = "apps/backend/.local-superusers.env"

if (Test-Path $seedFile) {
    Write-Host "[OK] Demo seed file exists."
    exit 0
}

$lines = @(
    "# Local demo credentials - NOT for production",
    "# Generated by create-seed.ps1 for one-click local startup.",
    "FREE_SUPERUSER_EMAIL=test@example.com",
    "FREE_SUPERUSER_PASSWORD=Test1234!",
    "FREE_SUPERUSER_FULL_NAME=Free Test User",
    "FREE_SUPERUSER_ORG_NAME=Test Shop",
    "",
    "PAID_SUPERUSER_EMAIL=test-su@example.com",
    "PAID_SUPERUSER_PASSWORD=Test1234!",
    "PAID_SUPERUSER_FULL_NAME=Paid Test User",
    "PAID_SUPERUSER_ORG_NAME=Super Test Shop",
    "PAID_SUPERUSER_PLAN=pro_monthly"
)

$utf8NoBOM = New-Object System.Text.UTF8Encoding $false
$absPath = Join-Path (Get-Location).Path $seedFile
[System.IO.File]::WriteAllLines($absPath, $lines, $utf8NoBOM)

Write-Host "[OK] Created demo seed file. Accounts seeded automatically on first start."
